"""Generate the JSON Schemas for the authoring DSLs.

The model schema is a build artifact, not hand-authored: its ``type`` enumerations
come straight from the ArchiMate 3.2 relationship matrix, so the DSL can never drift
from the oracle the semantic validator uses. The fact-register and entity-table
schemas are generated by the same mechanism so there is exactly one way schemas come
to exist. Regenerate with::

    python -m easkills gen-schema
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from . import oracle

SCHEMA_DIR = Path(__file__).resolve().parent.parent / "schema"
SCHEMA_PATH = SCHEMA_DIR / "model.schema.json"
FACTS_SCHEMA_PATH = SCHEMA_DIR / "facts.schema.json"
ENTITIES_SCHEMA_PATH = SCHEMA_DIR / "entities.schema.json"
STANDARD_SCHEMA_PATH = SCHEMA_DIR / "standard.schema.json"
DECISION_SCHEMA_PATH = SCHEMA_DIR / "decision.schema.json"
DISPENSATION_SCHEMA_PATH = SCHEMA_DIR / "dispensation.schema.json"
COMPLIANCE_SCHEMA_PATH = SCHEMA_DIR / "compliance.schema.json"
SERVICE_SCHEMA_PATH = SCHEMA_DIR / "service.schema.json"
REQUEST_SCHEMA_PATH = SCHEMA_DIR / "request.schema.json"

STANDARD_TYPES = ["legal", "industry", "organisation"]
STANDARD_LIFECYCLES = ["proposed", "trial", "active", "deprecated", "retired"]
DECISION_STATUSES = ["proposed", "accepted", "rejected", "deprecated", "superseded"]
# TOGAF's six architecture-compliance levels -- a spectrum, not pass/fail.
COMPLIANCE_VERDICTS = [
    "irrelevant",
    "consistent",
    "compliant",
    "conformant",
    "fully-conformant",
    "non-conformant",
]

SLUG_PATTERN = "^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$"
DATE_PATTERN = "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"


def build_schema() -> dict[str, Any]:
    element_types = sorted(oracle.element_types())
    relationship_types = sorted(oracle.relationship_types())

    provenance_item = {
        "oneOf": [
            {
                "type": "object",
                "additionalProperties": False,
                "required": ["file", "quote"],
                "properties": {
                    "file": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Path to the source document, relative to the repository root.",
                    },
                    "quote": {
                        "type": "string",
                        "minLength": 8,
                        "description": "Verbatim excerpt from that document; verified mechanically.",
                    },
                },
            },
            {
                "type": "object",
                "additionalProperties": False,
                "required": ["fact"],
                "properties": {
                    "fact": {
                        "$ref": "#/$defs/slug",
                        "description": (
                            "Id of a fact in facts/register/; the fact's own verified quotes "
                            "become this concept's evidence."
                        ),
                    },
                },
            },
        ],
    }

    common_properties: dict[str, Any] = {
        "id": {"$ref": "#/$defs/slug"},
        "name": {"type": "string", "minLength": 1, "maxLength": 120},
        "documentation": {"type": "string"},
        "owner": {"type": "string", "minLength": 1},
        "lastReviewed": {"type": "string", "pattern": DATE_PATTERN},
        "provenance": {
            "type": "array",
            "minItems": 1,
            "items": {"$ref": "#/$defs/provenance"},
        },
        "assumed": {
            "type": "boolean",
            "description": "True when the concept is not evidenced by a source; requires a rationale.",
        },
        "rationale": {"type": "string", "minLength": 1},
        "properties": {
            "type": "object",
            "additionalProperties": {"type": ["string", "number", "boolean", "null"]},
        },
    }

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:model",
        "title": "EA Skills model file",
        "description": (
            "One fragment of the enterprise architecture model. Enumerations are generated "
            f"from the vendored ArchiMate {oracle.matrix_version()} oracle."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "elements": {"type": "array", "items": {"$ref": "#/$defs/element"}},
            "relationships": {"type": "array", "items": {"$ref": "#/$defs/relationship"}},
            "views": {"type": "array", "items": {"$ref": "#/$defs/view"}},
            "stakeholders": {"type": "array", "items": {"$ref": "#/$defs/stakeholder"}},
            "concerns": {"type": "array", "items": {"$ref": "#/$defs/concern"}},
        },
        "$defs": {
            "slug": {
                "type": "string",
                "pattern": SLUG_PATTERN,
                "maxLength": 80,
                "description": "Stable author-supplied identifier; never regenerated.",
            },
            "provenance": provenance_item,
            "element": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "type", "name"],
                "properties": {
                    **common_properties,
                    "type": {"enum": element_types},
                    "appliesTo": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": (
                            "Motivation-layer applicability selector (AD-09): element ids this "
                            "requirement/constraint/principle/goal binds. Semantic checks: MOT001/MOT002."
                        ),
                    },
                    "standards": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": (
                            "Ids of SIB entries (standards/) this element follows. Lifecycle is "
                            "checked: deprecated warns, retired blocks unless a dispensation covers it."
                        ),
                    },
                },
            },
            "relationship": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "type", "source", "target"],
                "properties": {
                    **common_properties,
                    "name": {"type": "string", "maxLength": 120},
                    "type": {"enum": relationship_types},
                    "source": {"$ref": "#/$defs/slug"},
                    "target": {"$ref": "#/$defs/slug"},
                },
            },
            "view": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "name"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "name": {"type": "string", "minLength": 1, "maxLength": 120},
                    "documentation": {"type": "string"},
                    "viewpoint": {
                        "type": "string",
                        "description": "ArchiMate example viewpoint name, e.g. Layered or Capability Map.",
                    },
                    "include": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Element ids to show; connections are derived from the model.",
                    },
                    "concerns": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "ISO 42010: the declared concerns this view frames (ISO001/ISO005).",
                    },
                },
            },
            "stakeholder": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "name"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "name": {"type": "string", "minLength": 1, "maxLength": 120},
                    "description": {"type": "string"},
                    "concerns": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Concern ids this stakeholder holds (ISO 42010 6.3-6.4).",
                    },
                },
            },
            "concern": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "statement"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "statement": {
                        "type": "string",
                        "minLength": 8,
                        "maxLength": 300,
                        "description": "The interest, phrased as the question the views must answer.",
                    },
                },
            },
        },
    }


def build_facts_schema() -> dict[str, Any]:
    """Schema for facts/register/*.yaml -- the output contract of ea-intake.

    Note the deliberate absence of an ``assumed`` field: a fact without provenance is
    not valid. Unsourced knowledge belongs in clarification questions, or enters the
    model later as an explicit assumption there.
    """
    provenance_item = {
        "type": "object",
        "additionalProperties": False,
        "required": ["file", "quote"],
        "properties": {
            "file": {
                "type": "string",
                "minLength": 1,
                "description": "Path to the source document, relative to the repository root.",
            },
            "quote": {
                "type": "string",
                "minLength": 8,
                "description": "Verbatim excerpt from that document; verified mechanically.",
            },
        },
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:facts",
        "title": "EA Skills fact register file",
        "description": (
            "One fragment of the fact register: atomic, source-verified statements "
            "extracted from raw inputs before any ArchiMate typing happens."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "facts": {"type": "array", "items": {"$ref": "#/$defs/fact"}},
        },
        "$defs": {
            "slug": {
                "type": "string",
                "pattern": SLUG_PATTERN,
                "maxLength": 80,
                "description": "Stable author-supplied identifier; never regenerated.",
            },
            "provenance": provenance_item,
            "fact": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "statement", "provenance"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "statement": {
                        "type": "string",
                        "minLength": 8,
                        "maxLength": 500,
                        "description": "One atomic claim, in the register's own words.",
                    },
                    "provenance": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/provenance"},
                    },
                    "entities": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Entity ids (facts/entities.yaml) this fact mentions.",
                    },
                    "topics": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Free grouping tags, e.g. business, application, technology.",
                    },
                    "confidence": {
                        "enum": ["stated", "implied"],
                        "description": (
                            "'stated' when the quote says it directly; 'implied' when the quote "
                            "supports it only indirectly and a reviewer should look twice."
                        ),
                    },
                },
            },
        },
    }


def build_entities_schema() -> dict[str, Any]:
    """Schema for facts/entities.yaml -- the canonical-name and alias table."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:entities",
        "title": "EA Skills entity table",
        "description": (
            "Canonical names for things the sources mention, with the aliases they are "
            "mentioned by. One term resolves to exactly one entity; the validator enforces it."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "entities": {"type": "array", "items": {"$ref": "#/$defs/entity"}},
        },
        "$defs": {
            "slug": {
                "type": "string",
                "pattern": SLUG_PATTERN,
                "maxLength": 80,
            },
            "entity": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "name"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "name": {"type": "string", "minLength": 1, "maxLength": 120},
                    "kind": {
                        "type": "string",
                        "maxLength": 40,
                        "description": (
                            "Informal hint (application, process, actor, data, technology, ...). "
                            "Real ArchiMate typing happens in the modelling phase, not here."
                        ),
                    },
                    "aliases": {
                        "type": "array",
                        "items": {"type": "string", "minLength": 1, "maxLength": 120},
                        "uniqueItems": True,
                    },
                    "documentation": {"type": "string"},
                },
            },
        },
    }


def _slug_def() -> dict[str, Any]:
    return {
        "type": "string",
        "pattern": SLUG_PATTERN,
        "maxLength": 80,
    }


def build_standard_schema() -> dict[str, Any]:
    """One SIB entry per file under standards/ -- type, lifecycle, succession."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:standard",
        "title": "EA Skills standard (SIB entry)",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "name", "type", "lifecycle"],
        "properties": {
            "id": _slug_def(),
            "name": {"type": "string", "minLength": 1, "maxLength": 120},
            "type": {"enum": STANDARD_TYPES},
            "lifecycle": {
                "enum": STANDARD_LIFECYCLES,
                "description": "Referencing a deprecated standard warns; retired blocks unless a dispensation covers it.",
            },
            "description": {"type": "string"},
            "owner": {"type": "string", "minLength": 1},
            "url": {"type": "string", "minLength": 1},
            "successor": {
                **_slug_def(),
                "description": "The standard that replaces this one (expected once deprecated/retired).",
            },
            "lastReviewed": {"type": "string", "pattern": DATE_PATTERN},
        },
    }


def build_decision_schema() -> dict[str, Any]:
    """One MADR-shaped architecture decision record per file (ISO 42010 6.10 needs
    the rationale, so it is required, not polite)."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:decision",
        "title": "EA Skills architecture decision record",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "title", "status", "date", "decision", "rationale"],
        "properties": {
            "id": _slug_def(),
            "title": {"type": "string", "minLength": 1, "maxLength": 200},
            "status": {"enum": DECISION_STATUSES},
            "date": {"type": "string", "pattern": DATE_PATTERN},
            "context": {"type": "string"},
            "decision": {"type": "string", "minLength": 8},
            "rationale": {"type": "string", "minLength": 8},
            "consequences": {"type": "string"},
            "options": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["option"],
                    "properties": {
                        "option": {"type": "string", "minLength": 1},
                        "pros": {"type": "string"},
                        "cons": {"type": "string"},
                    },
                },
            },
            "supersededBy": _slug_def(),
            "relatedElements": {"type": "array", "items": _slug_def()},
        },
    }


def build_dispensation_schema() -> dict[str, Any]:
    """A time-bounded waiver. ``expires`` is required by schema, deliberately:
    a dispensation without an expiry is the tell of fake governance."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:dispensation",
        "title": "EA Skills dispensation",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "waives", "appliesTo", "rationale", "grantedBy", "granted", "expires"],
        "properties": {
            "id": _slug_def(),
            "title": {"type": "string", "maxLength": 200},
            "waives": {
                "type": "object",
                "additionalProperties": False,
                "minProperties": 1,
                "properties": {
                    "standard": {
                        **_slug_def(),
                        "description": "Standard whose retirement/deprecation is waived for the listed elements.",
                    },
                    "rule": {
                        "type": "string",
                        "maxLength": 40,
                        "description": "Validator rule code being waived (documented in the assessment).",
                    },
                },
            },
            "appliesTo": {"type": "array", "minItems": 1, "items": _slug_def()},
            "rationale": {"type": "string", "minLength": 8},
            "grantedBy": {"type": "string", "minLength": 1},
            "granted": {"type": "string", "pattern": DATE_PATTERN},
            "expires": {"type": "string", "pattern": DATE_PATTERN},
            "status": {"enum": ["open", "closed"]},
        },
    }


def build_compliance_schema() -> dict[str, Any]:
    """A compliance assessment with TOGAF's six-level verdict."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:compliance",
        "title": "EA Skills compliance assessment",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "subject", "date", "assessor", "verdict"],
        "properties": {
            "id": _slug_def(),
            "subject": {"type": "string", "minLength": 1, "maxLength": 200},
            "date": {"type": "string", "pattern": DATE_PATTERN},
            "assessor": {"type": "string", "minLength": 1},
            "verdict": {"enum": COMPLIANCE_VERDICTS},
            "findings": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "followUp": {
                "type": "object",
                "additionalProperties": False,
                "minProperties": 1,
                "properties": {
                    "dispensation": _slug_def(),
                    "decision": _slug_def(),
                    "notes": {"type": "string"},
                },
            },
            "relatedElements": {"type": "array", "items": _slug_def()},
        },
    }


def build_service_schema() -> dict[str, Any]:
    """One architecture-service offering per file under services/ (AD-10).

    The catalog is what turns EA from a gate into a provider: every offering has a
    named owner, a fulfilment path, and an SLA in days -- a promise with a number,
    so breaches are computable instead of felt.
    """
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:service",
        "title": "EA Skills architecture-service offering",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "name", "description", "fulfilledBy", "owner", "slaDays", "lifecycle"],
        "properties": {
            "id": _slug_def(),
            "name": {"type": "string", "minLength": 1, "maxLength": 120},
            "description": {
                "type": "string",
                "minLength": 8,
                "description": "What the consumer gets, phrased from the consumer's side.",
            },
            "fulfilledBy": {
                "type": "string",
                "minLength": 1,
                "description": "The skill and/or command that produces the deliverable, e.g. "
                "'ea-context / python -m easkills context --scope <id>'.",
            },
            "owner": {"type": "string", "minLength": 1},
            "slaDays": {
                "type": "integer",
                "minimum": 1,
                "maximum": 365,
                "description": "Promised working window from request to fulfilment.",
            },
            "lifecycle": {"enum": ["proposed", "active", "retired"]},
            "selfService": {
                "type": "boolean",
                "description": "True when the consumer can run the fulfilment themselves.",
            },
        },
    }


def build_request_schema() -> dict[str, Any]:
    """One service request per file under governance-log/requests/ -- the demand
    ledger. Architecture-as-a-Service is measured by consumption, and consumption
    that is not recorded cannot be measured."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:request",
        "title": "EA Skills service request",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "service", "requestedBy", "requested", "status"],
        "properties": {
            "id": _slug_def(),
            "service": {**_slug_def(), "description": "Offering id from services/."},
            "requestedBy": {"type": "string", "minLength": 1},
            "requested": {"type": "string", "pattern": DATE_PATTERN},
            "scope": {
                "type": "array",
                "minItems": 1,
                "items": _slug_def(),
                "description": "Element ids the request is about; drives demand-weighted maintenance.",
            },
            "status": {"enum": ["open", "fulfilled", "declined"]},
            "fulfilled": {"type": "string", "pattern": DATE_PATTERN},
            "fulfilledBy": {
                "type": "string",
                "minLength": 1,
                "description": "Pointer to the deliverable: a path, record id or URL.",
            },
            "notes": {"type": "string"},
        },
    }


def _write_json(target: Path, payload: dict[str, Any]) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" so regenerating on Windows does not rewrite every line ending and
    # bury the real change in a whole-file diff.
    target.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return target


def write_schema(path: Path | None = None) -> Path:
    return _write_json(path or SCHEMA_PATH, build_schema())


def write_all_schemas() -> list[Path]:
    return [
        _write_json(SCHEMA_PATH, build_schema()),
        _write_json(FACTS_SCHEMA_PATH, build_facts_schema()),
        _write_json(ENTITIES_SCHEMA_PATH, build_entities_schema()),
        _write_json(STANDARD_SCHEMA_PATH, build_standard_schema()),
        _write_json(DECISION_SCHEMA_PATH, build_decision_schema()),
        _write_json(DISPENSATION_SCHEMA_PATH, build_dispensation_schema()),
        _write_json(COMPLIANCE_SCHEMA_PATH, build_compliance_schema()),
        _write_json(SERVICE_SCHEMA_PATH, build_service_schema()),
        _write_json(REQUEST_SCHEMA_PATH, build_request_schema()),
    ]


def _load(target: Path, builder: Any) -> dict[str, Any]:
    if target.exists():
        return json.loads(target.read_text(encoding="utf-8"))
    return builder()


def load_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or SCHEMA_PATH, build_schema)


def load_facts_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or FACTS_SCHEMA_PATH, build_facts_schema)


def load_entities_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or ENTITIES_SCHEMA_PATH, build_entities_schema)


def load_standard_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or STANDARD_SCHEMA_PATH, build_standard_schema)


def load_decision_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or DECISION_SCHEMA_PATH, build_decision_schema)


def load_dispensation_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or DISPENSATION_SCHEMA_PATH, build_dispensation_schema)


def load_compliance_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or COMPLIANCE_SCHEMA_PATH, build_compliance_schema)


def load_service_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or SERVICE_SCHEMA_PATH, build_service_schema)


def load_request_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or REQUEST_SCHEMA_PATH, build_request_schema)
