"""Generate the JSON Schemas for the authoring DSLs.

The model schema is a build artifact, not hand-authored: its ``type`` enumerations
come straight from the ArchiMate 3.2 relationship matrix, so the DSL can never drift
from the oracle the semantic validator uses. The fact-register and entity-table
schemas are generated by the same mechanism so there is exactly one way schemas come
to exist. Regenerate with::

    python -m easkills gen-schema
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from . import oracle

SCHEMA_DIR = Path(__file__).resolve().parent.parent / "schema"
SCHEMA_PATH = SCHEMA_DIR / "model.schema.json"
FACTS_SCHEMA_PATH = SCHEMA_DIR / "facts.schema.json"
ENTITIES_SCHEMA_PATH = SCHEMA_DIR / "entities.schema.json"

SLUG_PATTERN = "^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$"
DATE_PATTERN = "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"


def build_schema() -> dict[str, Any]:
    element_types = sorted(oracle.element_types())
    relationship_types = sorted(oracle.relationship_types())

    provenance_item = {
        "type": "object",
        "additionalProperties": False,
        "required": ["file", "quote"],
        "properties": {
            "file": {
                "type": "string",
                "minLength": 1,
                "description": "Path to the source document, relative to the repository root.",
            },
            "quote": {
                "type": "string",
                "minLength": 8,
                "description": "Verbatim excerpt from that document; verified mechanically.",
            },
        },
    }

    common_properties: dict[str, Any] = {
        "id": {"$ref": "#/$defs/slug"},
        "name": {"type": "string", "minLength": 1, "maxLength": 120},
        "documentation": {"type": "string"},
        "owner": {"type": "string", "minLength": 1},
        "lastReviewed": {"type": "string", "pattern": DATE_PATTERN},
        "provenance": {
            "type": "array",
            "minItems": 1,
            "items": {"$ref": "#/$defs/provenance"},
        },
        "assumed": {
            "type": "boolean",
            "description": "True when the concept is not evidenced by a source; requires a rationale.",
        },
        "rationale": {"type": "string", "minLength": 1},
        "properties": {
            "type": "object",
            "additionalProperties": {"type": ["string", "number", "boolean", "null"]},
        },
    }

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:model",
        "title": "EA Skills model file",
        "description": (
            "One fragment of the enterprise architecture model. Enumerations are generated "
            f"from the vendored ArchiMate {oracle.matrix_version()} oracle."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "elements": {"type": "array", "items": {"$ref": "#/$defs/element"}},
            "relationships": {"type": "array", "items": {"$ref": "#/$defs/relationship"}},
            "views": {"type": "array", "items": {"$ref": "#/$defs/view"}},
        },
        "$defs": {
            "slug": {
                "type": "string",
                "pattern": SLUG_PATTERN,
                "maxLength": 80,
                "description": "Stable author-supplied identifier; never regenerated.",
            },
            "provenance": provenance_item,
            "element": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "type", "name"],
                "properties": {
                    **common_properties,
                    "type": {"enum": element_types},
                },
            },
            "relationship": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "type", "source", "target"],
                "properties": {
                    **common_properties,
                    "name": {"type": "string", "maxLength": 120},
                    "type": {"enum": relationship_types},
                    "source": {"$ref": "#/$defs/slug"},
                    "target": {"$ref": "#/$defs/slug"},
                },
            },
            "view": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "name"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "name": {"type": "string", "minLength": 1, "maxLength": 120},
                    "documentation": {"type": "string"},
                    "viewpoint": {
                        "type": "string",
                        "description": "ArchiMate example viewpoint name, e.g. Layered or Capability Map.",
                    },
                    "include": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Element ids to show; connections are derived from the model.",
                    },
                },
            },
        },
    }


def build_facts_schema() -> dict[str, Any]:
    """Schema for facts/register/*.yaml -- the output contract of ea-intake.

    Note the deliberate absence of an ``assumed`` field: a fact without provenance is
    not valid. Unsourced knowledge belongs in clarification questions, or enters the
    model later as an explicit assumption there.
    """
    provenance_item = {
        "type": "object",
        "additionalProperties": False,
        "required": ["file", "quote"],
        "properties": {
            "file": {
                "type": "string",
                "minLength": 1,
                "description": "Path to the source document, relative to the repository root.",
            },
            "quote": {
                "type": "string",
                "minLength": 8,
                "description": "Verbatim excerpt from that document; verified mechanically.",
            },
        },
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:facts",
        "title": "EA Skills fact register file",
        "description": (
            "One fragment of the fact register: atomic, source-verified statements "
            "extracted from raw inputs before any ArchiMate typing happens."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "facts": {"type": "array", "items": {"$ref": "#/$defs/fact"}},
        },
        "$defs": {
            "slug": {
                "type": "string",
                "pattern": SLUG_PATTERN,
                "maxLength": 80,
                "description": "Stable author-supplied identifier; never regenerated.",
            },
            "provenance": provenance_item,
            "fact": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "statement", "provenance"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "statement": {
                        "type": "string",
                        "minLength": 8,
                        "maxLength": 500,
                        "description": "One atomic claim, in the register's own words.",
                    },
                    "provenance": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/provenance"},
                    },
                    "entities": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Entity ids (facts/entities.yaml) this fact mentions.",
                    },
                    "topics": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Free grouping tags, e.g. business, application, technology.",
                    },
                    "confidence": {
                        "enum": ["stated", "implied"],
                        "description": (
                            "'stated' when the quote says it directly; 'implied' when the quote "
                            "supports it only indirectly and a reviewer should look twice."
                        ),
                    },
                },
            },
        },
    }


def build_entities_schema() -> dict[str, Any]:
    """Schema for facts/entities.yaml -- the canonical-name and alias table."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:entities",
        "title": "EA Skills entity table",
        "description": (
            "Canonical names for things the sources mention, with the aliases they are "
            "mentioned by. One term resolves to exactly one entity; the validator enforces it."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "entities": {"type": "array", "items": {"$ref": "#/$defs/entity"}},
        },
        "$defs": {
            "slug": {
                "type": "string",
                "pattern": SLUG_PATTERN,
                "maxLength": 80,
            },
            "entity": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "name"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "name": {"type": "string", "minLength": 1, "maxLength": 120},
                    "kind": {
                        "type": "string",
                        "maxLength": 40,
                        "description": (
                            "Informal hint (application, process, actor, data, technology, ...). "
                            "Real ArchiMate typing happens in the modelling phase, not here."
                        ),
                    },
                    "aliases": {
                        "type": "array",
                        "items": {"type": "string", "minLength": 1, "maxLength": 120},
                        "uniqueItems": True,
                    },
                    "documentation": {"type": "string"},
                },
            },
        },
    }


def _write_json(target: Path, payload: dict[str, Any]) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" so regenerating on Windows does not rewrite every line ending and
    # bury the real change in a whole-file diff.
    target.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return target


def write_schema(path: Path | None = None) -> Path:
    return _write_json(path or SCHEMA_PATH, build_schema())


def write_all_schemas() -> list[Path]:
    return [
        _write_json(SCHEMA_PATH, build_schema()),
        _write_json(FACTS_SCHEMA_PATH, build_facts_schema()),
        _write_json(ENTITIES_SCHEMA_PATH, build_entities_schema()),
    ]


def _load(target: Path, builder: Any) -> dict[str, Any]:
    if target.exists():
        return json.loads(target.read_text(encoding="utf-8"))
    return builder()


def load_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or SCHEMA_PATH, build_schema)


def load_facts_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or FACTS_SCHEMA_PATH, build_facts_schema)


def load_entities_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or ENTITIES_SCHEMA_PATH, build_entities_schema)
