"""Generate the JSON Schemas for the authoring DSLs.

The model schema is a build artifact, not hand-authored: its ``type`` enumerations
come straight from the ArchiMate 3.2 relationship matrix, so the DSL can never drift
from the oracle the semantic validator uses. The fact-register and entity-table
schemas are generated by the same mechanism so there is exactly one way schemas come
to exist. Regenerate with::

    python -m easkills gen-schema
"""

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

from . import oracle

SCHEMA_DIR = Path(__file__).resolve().parent.parent / "schema"
SCHEMA_PATH = SCHEMA_DIR / "model.schema.json"
FACTS_SCHEMA_PATH = SCHEMA_DIR / "facts.schema.json"
ENTITIES_SCHEMA_PATH = SCHEMA_DIR / "entities.schema.json"
STANDARD_SCHEMA_PATH = SCHEMA_DIR / "standard.schema.json"
DECISION_SCHEMA_PATH = SCHEMA_DIR / "decision.schema.json"
DISPENSATION_SCHEMA_PATH = SCHEMA_DIR / "dispensation.schema.json"
COMPLIANCE_SCHEMA_PATH = SCHEMA_DIR / "compliance.schema.json"
SERVICE_SCHEMA_PATH = SCHEMA_DIR / "service.schema.json"
REQUEST_SCHEMA_PATH = SCHEMA_DIR / "request.schema.json"
REFERENCE_SCHEMA_PATH = SCHEMA_DIR / "reference.schema.json"
REFERENCE_MAPPINGS_SCHEMA_PATH = SCHEMA_DIR / "reference-mappings.schema.json"
CONFIG_SCHEMA_PATH = SCHEMA_DIR / "ea-config.schema.json"

STANDARD_TYPES = ["legal", "industry", "organisation"]
STANDARD_LIFECYCLES = ["proposed", "trial", "active", "deprecated", "retired"]
DECISION_STATUSES = ["proposed", "accepted", "rejected", "deprecated", "superseded"]
# TOGAF's six architecture-compliance levels -- a spectrum, not pass/fail.
COMPLIANCE_VERDICTS = [
    "irrelevant",
    "consistent",
    "compliant",
    "conformant",
    "fully-conformant",
    "non-conformant",
]

# Gartner TIME quadrants, in reading order. The single vocabulary: the schema constrains
# `properties.timeDisposition` to it, docgen groups by it, kpi counts it.
TIME_DISPOSITIONS = ("Invest", "Migrate", "Tolerate", "Eliminate")

# Dependency manifests `ea-check` reads in a consuming repository (AD-09).
MANIFEST_KINDS = ("package.json", "pom.xml", "requirements.txt")

# What a reference-taxonomy node can be, and what a mapping may say about one. Closed
# vocabularies, for the reason `timeDisposition` is one: `align` reasons per kind, so a
# value it does not recognise would silently drop the node out of the report that reads it.
REFERENCE_NODE_KINDS = ("capability", "control", "process", "domain")
REFERENCE_MAPPING_STATUSES = ("covered", "partial", "out-of-scope")

# Regulatory registers this tool generates, and DORA's criticality vocabulary. Closed for
# the reason above, and one more: the failure mode of a *regulatory* register is
# under-inclusion. `regulatoryScope: DORA` as free text would drop the element out of the
# register silently, and nothing downstream would ever say so.
REGULATORY_SCOPES = ("dora", "ai-act")
CRITICALITIES = ("critical", "important", "standard")

# The EU AI Act vocabularies `ai-act-register` reads. Risk classes follow the Act's own
# structure (Art. 5 prohibited practices, Art. 6 high-risk, Art. 50 transparency-risk,
# everything else minimal); roles are the operators Art. 3 names. Closed for the same
# under-inclusion reason as `regulatoryScope`.
AI_RISK_CLASSES = ("prohibited", "high", "limited", "minimal")
AI_ROLES = (
    "provider",
    "deployer",
    "importer",
    "distributor",
    "product-manufacturer",
    "authorised-representative",
)


def regulatory_scope_values() -> tuple[str, ...]:
    """Every value ``regulatoryScope`` may carry: each scope alone, plus every
    multi-scope combination space-joined in alphabetical order.

    One element can genuinely sit in more than one register's scope -- an AI
    credit-scoring service bought from a vendor is DORA's ICT third-party risk *and* the
    AI Act's high-risk system. A single-valued enum would force a choice, and whichever
    register lost would lose silently -- the exact under-inclusion this vocabulary is
    closed against. The combinations stay enumerated (rather than free-ordered text) so
    a typo or a reordering still fails schema validation instead of dropping a row.
    """
    from itertools import combinations

    atoms = sorted(REGULATORY_SCOPES)
    values: list[str] = []
    for size in range(1, len(atoms) + 1):
        values.extend(" ".join(combo) for combo in combinations(atoms, size))
    return tuple(values)


def split_regulatory_scopes(value: Any) -> frozenset[str]:
    """The scopes a ``regulatoryScope`` value declares. Both registers read scope
    through this one function, so they cannot disagree about what a value means."""
    return frozenset(str(value or "").split())

SLUG_PATTERN = "^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$"
DATE_PATTERN = "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"


def build_schema() -> dict[str, Any]:
    element_types = sorted(oracle.element_types())
    relationship_types = sorted(oracle.relationship_types())

    provenance_item = {
        "oneOf": [
            {
                "type": "object",
                "additionalProperties": False,
                "required": ["file", "quote"],
                "properties": {
                    "file": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Path to the source document, relative to the repository root.",
                    },
                    "quote": {
                        "type": "string",
                        "minLength": 8,
                        "description": "Verbatim excerpt from that document; verified mechanically.",
                    },
                },
            },
            {
                "type": "object",
                "additionalProperties": False,
                "required": ["fact"],
                "properties": {
                    "fact": {
                        "$ref": "#/$defs/slug",
                        "description": (
                            "Id of a fact in facts/register/; the fact's own verified quotes "
                            "become this concept's evidence."
                        ),
                    },
                },
            },
        ],
    }

    common_properties: dict[str, Any] = {
        "id": {"$ref": "#/$defs/slug"},
        "name": {"type": "string", "minLength": 1, "maxLength": 120},
        "documentation": {"type": "string"},
        "owner": {"type": "string", "minLength": 1},
        "lastReviewed": {"type": "string", "pattern": DATE_PATTERN},
        "provenance": {
            "type": "array",
            "minItems": 1,
            "items": {"$ref": "#/$defs/provenance"},
        },
        "assumed": {
            "type": "boolean",
            "description": "True when the concept is not evidenced by a source; requires a rationale.",
        },
        "rationale": {"type": "string", "minLength": 1},
        "properties": {
            "type": "object",
            # The property map is deliberately open -- an organisation's own keys are its
            # own business. But keys this tooling *interprets* carry a vocabulary, because
            # a value it does not recognise is silently dropped from the report that reads
            # it: 'timeDisposition: tolerate' used to validate clean, count as
            # TIME-classified in the KPI, and vanish from the architecture description's
            # quadrant line, taking the whole application with it.
            "properties": {
                "timeDisposition": {
                    "enum": list(TIME_DISPOSITIONS),
                    "description": "Gartner TIME portfolio quadrant; read by 'docs' and 'kpi'.",
                },
                "plateauDate": {
                    "type": "string",
                    "pattern": DATE_PATTERN,
                    "description": (
                        "When a Plateau is reached; orders the roadmap. Read by 'roadmap' "
                        "and 'docs', checked by PLAT001-PLAT003."
                    ),
                },
                "regulatoryScope": {
                    "enum": list(regulatory_scope_values()),
                    "description": (
                        "Puts this element in one or more regulatory registers' scope. An "
                        "enum, not free text: 'DORA' or 'dora ' would silently drop the "
                        "element out of the register, and under-inclusion is the failure "
                        "mode that matters here. Multi-scope is declared as the "
                        "space-joined combination in alphabetical order ('ai-act dora'); "
                        "any other order or spelling is a schema error, never a silent "
                        "drop. Use your own property key for scopes this tool does not "
                        "generate a register for."
                    ),
                },
                "doraCriticality": {
                    "enum": list(CRITICALITIES),
                    "description": (
                        "DORA criticality of the function this element supports. Read by "
                        "'dora-register'; REG001 reports an in-scope element without one."
                    ),
                },
                "provider": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The ICT third-party service provider. Required on critical elements (REG002).",
                },
                "contractRef": {
                    "type": "string",
                    "minLength": 1,
                    "description": (
                        "Reference to the contractual arrangement covering this element. "
                        "Required on critical elements (REG002); the register lists it, it "
                        "never reads the contract."
                    ),
                },
                "aiRiskClass": {
                    "enum": list(AI_RISK_CLASSES),
                    "description": (
                        "EU AI Act risk classification of this system. Read by "
                        "'ai-act-register'; AIR001 reports an in-scope element without "
                        "one, and 'prohibited' is AIR005 -- a decision to surface, never "
                        "a row to file."
                    ),
                },
                "aiRole": {
                    "enum": list(AI_ROLES),
                    "description": (
                        "The operator role this organisation holds for the system, in the "
                        "AI Act's Art. 3 vocabulary. Required on high-risk elements "
                        "(AIR002) -- the obligations differ by role, so an inventory "
                        "without it cannot say which apply."
                    ),
                },
                "aiOversight": {
                    "type": "string",
                    "minLength": 1,
                    "description": (
                        "Who or what exercises human oversight over this system (Art. 14): "
                        "a role, a committee, a named procedure. Required on high-risk "
                        "elements (AIR002); the register lists it, it never audits it."
                    ),
                },
            },
            "additionalProperties": {"type": ["string", "number", "boolean", "null"]},
        },
    }

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:model",
        "title": "EA Skills model file",
        "description": (
            "One fragment of the enterprise architecture model. Enumerations are generated "
            f"from the vendored ArchiMate {oracle.matrix_version()} oracle."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "elements": {"type": "array", "items": {"$ref": "#/$defs/element"}},
            "relationships": {"type": "array", "items": {"$ref": "#/$defs/relationship"}},
            "views": {"type": "array", "items": {"$ref": "#/$defs/view"}},
            "stakeholders": {"type": "array", "items": {"$ref": "#/$defs/stakeholder"}},
            "concerns": {"type": "array", "items": {"$ref": "#/$defs/concern"}},
        },
        "$defs": {
            "slug": {
                "type": "string",
                "pattern": SLUG_PATTERN,
                "maxLength": 80,
                "description": "Stable author-supplied identifier; never regenerated.",
            },
            "provenance": provenance_item,
            "element": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "type", "name"],
                "properties": {
                    **common_properties,
                    "type": {"enum": element_types},
                    "appliesTo": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": (
                            "Motivation-layer applicability selector (AD-09): element ids this "
                            "requirement/constraint/principle/goal binds. Semantic checks: MOT001/MOT002."
                        ),
                    },
                    "standards": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": (
                            "Ids of SIB entries (standards/) this element follows. Lifecycle is "
                            "checked: deprecated warns, retired blocks unless a dispensation covers it."
                        ),
                    },
                },
            },
            "relationship": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "type", "source", "target"],
                "properties": {
                    **common_properties,
                    "name": {"type": "string", "maxLength": 120},
                    "type": {"enum": relationship_types},
                    "source": {"$ref": "#/$defs/slug"},
                    "target": {"$ref": "#/$defs/slug"},
                },
            },
            "view": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "name"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "name": {"type": "string", "minLength": 1, "maxLength": 120},
                    "documentation": {"type": "string"},
                    "viewpoint": {
                        "type": "string",
                        "description": "ArchiMate example viewpoint name, e.g. Layered or Capability Map.",
                    },
                    "include": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Element ids to show; connections are derived from the model.",
                    },
                    "concerns": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "ISO 42010: the declared concerns this view frames (ISO001/ISO005).",
                    },
                },
            },
            "stakeholder": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "name"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "name": {"type": "string", "minLength": 1, "maxLength": 120},
                    "description": {"type": "string"},
                    "concerns": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Concern ids this stakeholder holds (ISO 42010 6.3-6.4).",
                    },
                },
            },
            "concern": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "statement"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "statement": {
                        "type": "string",
                        "minLength": 8,
                        "maxLength": 300,
                        "description": "The interest, phrased as the question the views must answer.",
                    },
                },
            },
        },
    }


def build_facts_schema() -> dict[str, Any]:
    """Schema for facts/register/*.yaml -- the output contract of ea-intake.

    Note the deliberate absence of an ``assumed`` field: a fact without provenance is
    not valid. Unsourced knowledge belongs in clarification questions, or enters the
    model later as an explicit assumption there.
    """
    provenance_item = {
        "type": "object",
        "additionalProperties": False,
        "required": ["file", "quote"],
        "properties": {
            "file": {
                "type": "string",
                "minLength": 1,
                "description": "Path to the source document, relative to the repository root.",
            },
            "quote": {
                "type": "string",
                "minLength": 8,
                "description": "Verbatim excerpt from that document; verified mechanically.",
            },
        },
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:facts",
        "title": "EA Skills fact register file",
        "description": (
            "One fragment of the fact register: atomic, source-verified statements "
            "extracted from raw inputs before any ArchiMate typing happens."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "facts": {"type": "array", "items": {"$ref": "#/$defs/fact"}},
        },
        "$defs": {
            "slug": {
                "type": "string",
                "pattern": SLUG_PATTERN,
                "maxLength": 80,
                "description": "Stable author-supplied identifier; never regenerated.",
            },
            "provenance": provenance_item,
            "fact": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "statement", "provenance"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "statement": {
                        "type": "string",
                        "minLength": 8,
                        "maxLength": 500,
                        "description": "One atomic claim, in the register's own words.",
                    },
                    "provenance": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/provenance"},
                    },
                    "entities": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Entity ids (facts/entities.yaml) this fact mentions.",
                    },
                    "topics": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Free grouping tags, e.g. business, application, technology.",
                    },
                    "contests": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": (
                            "Ids of facts this one contradicts. Required when confidence is "
                            "'contested': a contradiction nobody can follow is hinted at, not recorded."
                        ),
                    },
                    "confidence": {
                        "enum": ["stated", "implied", "contested"],
                        "description": (
                            "'stated' when the quote says it directly; 'implied' when the quote "
                            "supports it only indirectly and a reviewer should look twice; "
                            "'contested' when another source says the opposite -- both sides stay "
                            "in the register and 'contests' names the other one."
                        ),
                    },
                },
            },
        },
    }


def build_entities_schema() -> dict[str, Any]:
    """Schema for facts/entities.yaml -- the canonical-name and alias table."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:entities",
        "title": "EA Skills entity table",
        "description": (
            "Canonical names for things the sources mention, with the aliases they are "
            "mentioned by. One term resolves to exactly one entity; the validator enforces it."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "entities": {"type": "array", "items": {"$ref": "#/$defs/entity"}},
        },
        "$defs": {
            "slug": {
                "type": "string",
                "pattern": SLUG_PATTERN,
                "maxLength": 80,
            },
            "entity": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "name"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "name": {"type": "string", "minLength": 1, "maxLength": 120},
                    "kind": {
                        "type": "string",
                        "maxLength": 40,
                        "description": (
                            "Informal hint (application, process, actor, data, technology, ...). "
                            "Real ArchiMate typing happens in the modelling phase, not here."
                        ),
                    },
                    "aliases": {
                        "type": "array",
                        "items": {"type": "string", "minLength": 1, "maxLength": 120},
                        "uniqueItems": True,
                    },
                    "documentation": {"type": "string"},
                },
            },
        },
    }


def _slug_def() -> dict[str, Any]:
    return {
        "type": "string",
        "pattern": SLUG_PATTERN,
        "maxLength": 80,
    }


def build_standard_schema() -> dict[str, Any]:
    """One SIB entry per file under standards/ -- type, lifecycle, succession."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:standard",
        "title": "EA Skills standard (SIB entry)",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "name", "type", "lifecycle"],
        "properties": {
            "id": _slug_def(),
            "name": {"type": "string", "minLength": 1, "maxLength": 120},
            "type": {"enum": STANDARD_TYPES},
            "lifecycle": {
                "enum": STANDARD_LIFECYCLES,
                "description": "Referencing a deprecated standard warns; retired blocks unless a dispensation covers it.",
            },
            "description": {"type": "string"},
            "owner": {"type": "string", "minLength": 1},
            "url": {"type": "string", "minLength": 1},
            "successor": {
                **_slug_def(),
                "description": "The standard that replaces this one (expected once deprecated/retired).",
            },
            "lastReviewed": {"type": "string", "pattern": DATE_PATTERN},
            "detect": {
                "type": "array",
                "description": (
                    "How a consuming repository evidences this standard, for 'ea-check'. "
                    "Matching is by dependency name; versions are reported, never interpreted."
                ),
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["manifest", "dependency"],
                    "properties": {
                        "manifest": {"enum": list(MANIFEST_KINDS)},
                        "dependency": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Package name; 'groupId:artifactId' for pom.xml.",
                        },
                        "note": {"type": "string"},
                    },
                },
            },
        },
    }


def build_decision_schema() -> dict[str, Any]:
    """One MADR-shaped architecture decision record per file (ISO 42010 6.10 needs
    the rationale, so it is required, not polite)."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:decision",
        "title": "EA Skills architecture decision record",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "title", "status", "date", "decision", "rationale"],
        "properties": {
            "id": _slug_def(),
            "title": {"type": "string", "minLength": 1, "maxLength": 200},
            "status": {"enum": DECISION_STATUSES},
            "date": {"type": "string", "pattern": DATE_PATTERN},
            "context": {"type": "string"},
            "decision": {"type": "string", "minLength": 8},
            "rationale": {"type": "string", "minLength": 8},
            "consequences": {"type": "string"},
            "options": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["option"],
                    "properties": {
                        "option": {"type": "string", "minLength": 1},
                        "pros": {"type": "string"},
                        "cons": {"type": "string"},
                    },
                },
            },
            "supersededBy": _slug_def(),
            "relatedElements": {"type": "array", "items": _slug_def()},
        },
    }


def build_dispensation_schema() -> dict[str, Any]:
    """A time-bounded waiver. ``expires`` is required by schema, deliberately:
    a dispensation without an expiry is the tell of fake governance."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:dispensation",
        "title": "EA Skills dispensation",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "waives", "appliesTo", "rationale", "grantedBy", "granted", "expires"],
        "properties": {
            "id": _slug_def(),
            "title": {"type": "string", "maxLength": 200},
            "waives": {
                "type": "object",
                "additionalProperties": False,
                "minProperties": 1,
                "properties": {
                    "standard": {
                        **_slug_def(),
                        "description": "Standard whose retirement/deprecation is waived for the listed elements.",
                    },
                    "rule": {
                        "type": "string",
                        "maxLength": 40,
                        "description": "Validator rule code being waived (documented in the assessment).",
                    },
                },
            },
            "appliesTo": {"type": "array", "minItems": 1, "items": _slug_def()},
            "rationale": {"type": "string", "minLength": 8},
            "grantedBy": {"type": "string", "minLength": 1},
            "granted": {"type": "string", "pattern": DATE_PATTERN},
            "expires": {"type": "string", "pattern": DATE_PATTERN},
            "status": {"enum": ["open", "closed"]},
        },
    }


def build_compliance_schema() -> dict[str, Any]:
    """A compliance assessment with TOGAF's six-level verdict."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:compliance",
        "title": "EA Skills compliance assessment",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "subject", "date", "assessor", "verdict"],
        "properties": {
            "id": _slug_def(),
            "subject": {"type": "string", "minLength": 1, "maxLength": 200},
            "date": {"type": "string", "pattern": DATE_PATTERN},
            "assessor": {"type": "string", "minLength": 1},
            "verdict": {"enum": COMPLIANCE_VERDICTS},
            "findings": {"type": "array", "items": {"type": "string", "minLength": 1}},
            "followUp": {
                "type": "object",
                "additionalProperties": False,
                "minProperties": 1,
                "properties": {
                    "dispensation": _slug_def(),
                    "decision": _slug_def(),
                    "notes": {"type": "string"},
                },
            },
            "relatedElements": {"type": "array", "items": _slug_def()},
        },
    }


def build_service_schema() -> dict[str, Any]:
    """One architecture-service offering per file under services/ (AD-10).

    The catalog is what turns EA from a gate into a provider: every offering has a
    named owner, a fulfilment path, and an SLA in days -- a promise with a number,
    so breaches are computable instead of felt.
    """
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:service",
        "title": "EA Skills architecture-service offering",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "name", "description", "fulfilledBy", "owner", "slaDays", "lifecycle"],
        "properties": {
            "id": _slug_def(),
            "name": {"type": "string", "minLength": 1, "maxLength": 120},
            "description": {
                "type": "string",
                "minLength": 8,
                "description": "What the consumer gets, phrased from the consumer's side.",
            },
            "fulfilledBy": {
                "type": "string",
                "minLength": 1,
                "description": "The skill and/or command that produces the deliverable, e.g. "
                "'ea-context / python -m easkills context --scope <id>'.",
            },
            "owner": {"type": "string", "minLength": 1},
            "slaDays": {
                "type": "integer",
                "minimum": 1,
                "maximum": 365,
                "description": "Promised working window from request to fulfilment.",
            },
            "lifecycle": {"enum": ["proposed", "active", "retired"]},
            "selfService": {
                "type": "boolean",
                "description": "True when the consumer can run the fulfilment themselves.",
            },
        },
    }


def build_request_schema() -> dict[str, Any]:
    """One service request per file under governance-log/requests/ -- the demand
    ledger. Architecture-as-a-Service is measured by consumption, and consumption
    that is not recorded cannot be measured."""
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:request",
        "title": "EA Skills service request",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "service", "requestedBy", "requested", "status"],
        "properties": {
            "id": _slug_def(),
            "service": {**_slug_def(), "description": "Offering id from services/."},
            "requestedBy": {"type": "string", "minLength": 1},
            "requested": {"type": "string", "pattern": DATE_PATTERN},
            "scope": {
                "type": "array",
                "minItems": 1,
                "items": _slug_def(),
                "description": "Element ids the request is about; drives demand-weighted maintenance.",
            },
            "status": {"enum": ["open", "fulfilled", "declined"]},
            "fulfilled": {"type": "string", "pattern": DATE_PATTERN},
            "fulfilledBy": {
                "type": "string",
                "minLength": 1,
                "description": "Pointer to the deliverable: a path, record id or URL.",
            },
            "notes": {"type": "string"},
        },
    }


def build_reference_schema() -> dict[str, Any]:
    """Schema for ``reference/<name>/model.yaml`` -- a hash-pinned reference taxonomy.

    Deliberately *not* a model: nodes carry a `parent` and nothing else relational. No
    relationships, no behaviour, no properties this tooling would then have to interpret.
    Edges between architecture elements are what `model/` is for, and the ArchiMate
    oracle governs them; a reference model that grew edges would be a second metamodel
    with no oracle behind it.

    Note the absence of ``minItems`` on ``nodes``: an empty pack is reported by
    ``ALN008``, which can say *why* an empty yardstick is worse than none, where a
    schema error could only say the array was too short.
    """
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:reference",
        "title": "EA Skills reference taxonomy",
        "description": (
            "One reference architecture or industry blueprint, as a taxonomy of nodes the "
            "local model is measured against. Hash-pinned: the tooling refuses to read a "
            "pack whose SHA256SUMS do not match (ALN001)."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": ["name", "nodes"],
        "properties": {
            "name": {
                "type": "string",
                "minLength": 1,
                "maxLength": 120,
                "description": "Human name of the reference model, e.g. 'NIST CSF 2.0'.",
            },
            "version": {
                "type": "string",
                "maxLength": 40,
                "description": "The edition this pack transcribes; part of what the NOTICE cites.",
            },
            "source": {
                "type": "string",
                "maxLength": 300,
                "description": "Where the taxonomy came from. Licence terms live in NOTICE.md.",
            },
            "nodes": {"type": "array", "items": {"$ref": "#/$defs/node"}},
        },
        "$defs": {
            "slug": _slug_def(),
            "node": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id", "name", "kind"],
                "properties": {
                    "id": {"$ref": "#/$defs/slug"},
                    "name": {"type": "string", "minLength": 1, "maxLength": 200},
                    "kind": {
                        "enum": list(REFERENCE_NODE_KINDS),
                        "description": "What the node is; `align` reads local elements per kind.",
                    },
                    "parent": {
                        **_slug_def(),
                        "description": (
                            "Id of the node this one decomposes. The only relation a taxonomy has: "
                            "out-of-scope decisions inherit down it, coverage claims do not."
                        ),
                    },
                    "description": {"type": "string", "maxLength": 1000},
                    "externalId": {
                        "type": "string",
                        "maxLength": 40,
                        "description": "The code the source publishes, e.g. 'GV.OC'. Printed in reports.",
                    },
                },
            },
        },
    }


def build_reference_mappings_schema() -> dict[str, Any]:
    """Schema for ``reference/<name>/mappings.yaml`` -- the human-authored judgement.

    ``elements`` is required for a coverage claim (a claim with nothing behind it is not
    a claim), but ``rationale`` is **not** required for ``out-of-scope``: that case is
    reported by ``ALN005`` instead, so a missing rationale reads as the governance
    finding it is rather than as a formatting error. It is the one place here where a
    weaker schema is the more honest design.
    """
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:reference-mappings",
        "title": "EA Skills reference mappings",
        "description": (
            "What local model content answers each node of a reference taxonomy, or why a "
            "node is out of this architecture's scope. Authored by a human; never generated."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": ["mappings"],
        "properties": {
            "mappings": {"type": "array", "items": {"$ref": "#/$defs/mapping"}},
        },
        "$defs": {
            "slug": _slug_def(),
            "mapping": {
                "type": "object",
                "additionalProperties": False,
                "required": ["ref", "status"],
                "properties": {
                    "ref": {**_slug_def(), "description": "Id of the reference node this entry judges."},
                    "status": {
                        "enum": list(REFERENCE_MAPPING_STATUSES),
                        "description": (
                            "'covered' when local content answers the node; 'partial' when it "
                            "answers part of it (counts half); 'out-of-scope' when the "
                            "architecture deliberately does not cover it."
                        ),
                    },
                    "elements": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/slug"},
                        "description": "Local element ids that answer this node.",
                    },
                    "note": {
                        "type": "string",
                        "maxLength": 500,
                        "description": "Why this mapping is the judgement it is -- especially for 'partial'.",
                    },
                    "rationale": {
                        "type": "string",
                        "maxLength": 500,
                        "description": "Mandatory for 'out-of-scope' (enforced by ALN005, not here).",
                    },
                },
                "allOf": [
                    {
                        "if": {
                            "required": ["status"],
                            "properties": {"status": {"enum": ["covered", "partial"]}},
                        },
                        "then": {"required": ["elements"]},
                    }
                ],
            },
        },
    }


# The rate keys `costModel` accepts, and the exposure each one prices. The tuple is the
# single definition: `easkills/cost.py` derives one quantity per key, this schema accepts
# exactly these keys, and a test pins the two against each other -- so a rate that prices
# nothing, or an exposure with no way to price it, cannot ship.
COST_RATE_KEYS: tuple[tuple[str, str], ...] = (
    ("staleElementDay", "Per element, per day past `stalenessDays`."),
    ("openDispensationDay", "Per open dispensation, per day since it was granted."),
    ("eolElement", "Per element referencing a deprecated or retired standard."),
    ("unsupportedCapability", "Per capability nothing realizes."),
    ("duplicateRealization", "Per realizer beyond the first on one capability."),
)


def build_config_schema() -> dict[str, Any]:
    """``ea.config.yaml``.

    Strict on both levels, unlike an element's open ``properties`` map. A model's own
    property keys are the organisation's business; a *tooling* config key that the
    tooling does not read is always a defect -- ``stalenessDay`` silently leaves the
    documented 365-day default in place, and the repository looks fresh because nothing
    said otherwise. Ranges live here as well as in ``dsl.config_number`` so a
    schema-aware editor flags ``quoteMatchThreshold: 90`` while it is being typed;
    ``check_config`` reports each key once (see SCHEMA002).
    """
    rates = {
        key: {
            "type": "number",
            "minimum": 0,
            "description": description,
        }
        for key, description in COST_RATE_KEYS
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "urn:ea-skills:schema:ea-config",
        "title": "EA Skills repository configuration",
        "description": "Repository-level settings. Every key is optional; the documented default applies.",
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "name": {"type": "string", "minLength": 1, "description": "Model name, used in generated documents."},
            "documentation": {"type": "string", "description": "What this model covers and what it is for."},
            "stalenessDays": {
                "type": "integer",
                "minimum": 1,
                "description": "Elements not reviewed within this many days are stale (GOV004, `staleness`).",
            },
            "quoteMatchThreshold": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "description": "Minimum similarity for a provenance quote to count as approximate (PROV004).",
            },
            "factsRoot": {"type": "string", "description": "Directory provenance file references resolve against."},
            "sourcesDir": {"type": "string", "description": "Directory holding the raw source documents."},
            "costModel": {
                "type": "object",
                "additionalProperties": False,
                "required": ["currency"],
                "description": (
                    "Optional. Unit rates that turn the debt register's exposure into money. "
                    "The tool computes the exposure; the operator prices it. Absent, `debt` "
                    "output is unchanged."
                ),
                "properties": {
                    "currency": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 8,
                        "description": (
                            "Printed beside every amount. Required, because an unlabelled "
                            "number in a board pack is read in whatever currency the reader "
                            "assumes."
                        ),
                    },
                    **rates,
                },
            },
        },
    }


def _write_json(target: Path, payload: dict[str, Any]) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" so regenerating on Windows does not rewrite every line ending and
    # bury the real change in a whole-file diff.
    target.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return target


def write_schema(path: Path | None = None) -> Path:
    return _write_json(path or SCHEMA_PATH, build_schema())


# The single registry of generated schemas: ``gen-schema`` writes exactly these, and the
# freshness test iterates the same tuple -- so a tenth schema cannot be added with only
# nine of them checked against their committed copies.
SCHEMAS: tuple[tuple[Path, Callable[[], dict[str, Any]]], ...] = (
    (SCHEMA_PATH, build_schema),
    (FACTS_SCHEMA_PATH, build_facts_schema),
    (ENTITIES_SCHEMA_PATH, build_entities_schema),
    (STANDARD_SCHEMA_PATH, build_standard_schema),
    (DECISION_SCHEMA_PATH, build_decision_schema),
    (DISPENSATION_SCHEMA_PATH, build_dispensation_schema),
    (COMPLIANCE_SCHEMA_PATH, build_compliance_schema),
    (SERVICE_SCHEMA_PATH, build_service_schema),
    (REQUEST_SCHEMA_PATH, build_request_schema),
    (REFERENCE_SCHEMA_PATH, build_reference_schema),
    (REFERENCE_MAPPINGS_SCHEMA_PATH, build_reference_mappings_schema),
    (CONFIG_SCHEMA_PATH, build_config_schema),
)


def write_all_schemas() -> list[Path]:
    return [_write_json(path, builder()) for path, builder in SCHEMAS]


def _load(target: Path, builder: Any) -> dict[str, Any]:
    if target.exists():
        return json.loads(target.read_text(encoding="utf-8"))
    return builder()


def load_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or SCHEMA_PATH, build_schema)


def load_facts_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or FACTS_SCHEMA_PATH, build_facts_schema)


def load_entities_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or ENTITIES_SCHEMA_PATH, build_entities_schema)


def load_standard_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or STANDARD_SCHEMA_PATH, build_standard_schema)


def load_decision_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or DECISION_SCHEMA_PATH, build_decision_schema)


def load_dispensation_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or DISPENSATION_SCHEMA_PATH, build_dispensation_schema)


def load_compliance_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or COMPLIANCE_SCHEMA_PATH, build_compliance_schema)


def load_service_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or SERVICE_SCHEMA_PATH, build_service_schema)


def load_request_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or REQUEST_SCHEMA_PATH, build_request_schema)


def load_reference_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or REFERENCE_SCHEMA_PATH, build_reference_schema)


def load_reference_mappings_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or REFERENCE_MAPPINGS_SCHEMA_PATH, build_reference_mappings_schema)


def load_config_schema(path: Path | None = None) -> dict[str, Any]:
    return _load(path or CONFIG_SCHEMA_PATH, build_config_schema)
